### PR TITLE
Added Image Conversion from Pixels to ASCII art

### PR DESCRIPTION
**Pull request by anayra-c6b9**
# Pull Request Template

**Feature Name:** IMAGE CONVERSION FROM PIXELS TO ASCII ART

**Changes made:**
Created an IMAGE_TO_ASCII_ART in Projects folder. The main.py script can change a regular picture to an ASCII art, displays the ASCII art in console and saves the art in the form of text document. The code takes user preferable dimensions to create the art.

### Self Check(Tick After Making pull Request)

- [x] I have read and followed the [Contribution Guidelines](/CONTRIBUTING.md)
- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder

- [x] PR is regarding Code
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I am using external libraries and I have created requirements.txt in my project folder
- [x] Script is tested and running perfectly fine on my system

- [ ] PR is regarding the documentation

> If the issue was not assigned to you Please don't make a PR, It will be marked as invalid.

Discuss in discord server:- http://pragmaticprogrammer.in/discord

## acknowledgment
- [x] I have tested my code and distributing it under GPL-3.0 License

### CODE REVIEW

**Review by Punit-Choudhary — CHANGES_REQUESTED** [review]
Invalid requirements.txt!
Please edit this requirements.txt with proper syntax.
Refer to [this documentation](https://pip.pypa.io/en/stable/reference/requirements-file-format/) for a proper format.

**Comment by anayra-c6b9** [comment]
@Punit-Choudhary Changes made. Please check the requirements.txt. Thankyou.

**Comment by Punit-Choudhary** [comment]
@anayra-c6b9 Linting failed, please resolve them and commit changes.
Tip: You can join our discord if you're looking for a helping hand 🫂

**Review by Punit-Choudhary — APPROVED** [review]

**Comment by anayra-c6b9** [comment]
@Punit-Choudhary Sorry for such a hard time. This is my first time using git properly and I'm learning a lot. Thankyou

**Comment by anayra-c6b9** [comment]
I accidently requested to merge the forked repository to main. Sorry for that one. I dont know how to undo it

**Comment by Punit-Choudhary** [comment]
@anayra-c6b9 Thank you for your contribution 💜 
Glad to know that you're getting something to learn through this project 🙂

**Pull request merged**
