### PR TITLE
Created BlackJack Card Game

### PR DESCRIPTION
**Pull request by Money-20**
# Pull Request Template

**Feature Name:**  BLACKJACK CARD GAME

**Changes made:** 
Created a Text-Based terminal Game using python 

### Self Check(Tick After Making pull Request)

- [x] I have read and followed the [Contribution Guidelines](/CONTRIBUTING.md)
- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder

- [x] PR is regarding Code
- [x] I am following clean code and Documentation and my code is well-linted with flake8.
- [ ] I am using external libraries and I have created requirements.txt in my project folder
- [x] Script is tested and running perfectly fine on my system

- [ ] PR is regarding the documentation

> If the issue was not assigned to you Please don't make a PR, It will be marked as invalid.

Discuss in discord server:- http://pragmaticprogrammer.in/discord

## acknowledgment
- [x] I have tested my code and distributing it under GPL-3.0 License

### CODE REVIEW

**Comment by Punit-Choudhary** [comment]
Hey @Money-20 
Lint check failed, please lint (format) your code and commit changes.

**Comment by Money-20** [comment]
Thanks for pointing it out. I will lint the codebase.

**Review by Money-20 — COMMENTED** [review]
Linted the code Based on flake8 norms

**Comment by Money-20** [comment]
@Punit-Choudhary  Can you review the changes...

**Review by Punit-Choudhary — APPROVED** [review]

**Comment by Punit-Choudhary** [comment]
Thank you for the contribution 💜 🚀

**Pull request merged**
