### PR TITLE
Create Area_of_triangles_sides.py

### PR DESCRIPTION
**Pull request by MrB141107**
This program helps the user to calculate the area of a triangle by giving measurements of sides.

# Pull Request Template

### Self Check(Tick After Making pull Request)

- [x] I have read and followed the [Contribution Guidelines](/CONTRIBUTING.md)
- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder

- [x] PR is regarding Code
- [x] I am following clean code and Documentation and my code is well-linked with flake8.
- [ ] I am using external libraries and I have created requirements.txt in my project folder
- [x] Script is tested and running perfectly fine on my system

Discuss in discord server:- http://pragmaticprogrammer.in/discord

## Acknowledgment
- [x] I have tested my code and distributed it under GPL-3.0 License

### CODE REVIEW

**Comment by MrB141107** [comment]
@Punit-Choudhary, I would like to have a review on this PR regarding the recent issue #257

**Comment by Punit-Choudhary** [comment]
Hey @MrB141107, Please lint your code with flake8 or any other linting tool.
Online recommended tool: [Code Beautify](https://codebeautify.org/python-formatter-beautifier)

**Comment by MrB141107** [comment]
@Punit-Choudhary, I haven't done linting code earlier, I would like to request you to help me out with it, how can I lint my code with flake8

**Comment by Punit-Choudhary** [comment]
Hey @MrB141107, It is very well described in this [Blog](https://medium.com/python-pandemonium/what-is-flake8-and-why-we-should-use-it-b89bd78073f2). I would suggest using online tools like [CodeBeautify](https://codebeautify.org/python-formatter-beautifier) as they auto-lint your code. Feel free to ask if you need any help with this.

**Comment by MrB141107** [comment]
@Punit-Choudhary, I have updated the code using CodeBeautify as you suggested. Now, can you help me out with the further process...

**Review by Punit-Choudhary — APPROVED** [review]

**Comment by Punit-Choudhary** [comment]
Thank you for your contribution 🎉💜

**Comment by MrB141107** [comment]
@Punit-Choudhary, Thank you so much for merging the PR 🎇 ✨ 

I would like to request you to visit my repo [Python_Projects](https://github.com/MrB141107/Python_Projects).

**Pull request merged**
