### PR TITLE
Added 3D Cube Visualizer

### PR DESCRIPTION
**Pull request by codingis4noobs2**
# Pull Request Template

**3D Cube Visualizer**

**Changes made:**<br>
Added Visualizer3D_Cube in ` Python-beginner-scripts/Projects/ `

### Self Check(Tick After Making pull Request)

- [x] I have read and followed the [Contribution Guidelines](/CONTRIBUTING.md)
- [x] This issue was assigned to me.
- [x] One Change in one Pull Request
- [x] My file is in the proper folder

- [x] PR is regarding Code
- [x] I am following clean code and Documentation and my code is well linted with flake8.
- [x] I am using external libraries and I have created requirements.txt in my project folder
- [x] Script is tested and running perfectly fine on my system

- [ ] PR is regarding the documentation

> If the issue was not assigned to you Please don't make a PR, It will be marked as invalid.

Discuss in discord server:- http://pragmaticprogrammer.in/discord

## acknowledgment
- [x] I have tested my code and distributing it under GPL-3.0 License

### CODE REVIEW

**Comment by Punit-Choudhary** [comment]
Please add `requirements.txt`

**Comment by codingis4noobs2** [comment]
Done @Punit-Choudhary

**Comment by Punit-Choudhary** [comment]
Linting failed, please resolve them and commit changes.
You may join our discord server if you need any help 🥲

**Comment by codingis4noobs2** [comment]
Solved Linting Issues :) @Punit-Choudhary

**Comment by Punit-Choudhary** [comment]
I tried running the program, but it seems not working on my end.
It is just showing a black screen.

**Comment by codingis4noobs2** [comment]
Pygame has a bug or some issue due to which if you run sometime you will get black screen

**Comment by codingis4noobs2** [comment]
it works
image

**Pull request merged**
