### PR TITLE
Symbol Pattern 2

### PR DESCRIPTION
**Pull request by helloshiv01**
Feature Name:Symbol Pattern 2

Changes made:

mention your changes here:
added code for pattern number 2 and made linting changes

Issue num (must) - #201
 
Self Check(Tick After Making pull Request)

- [x] I have read and followed the [Contribution Guidelines](https://github.com/CONTRIBUTING.md)

 - [x] This issue was assigned to me.

 - [x] One Change in one Pull Request

- [x] My file is in the proper folder

 - [x] PR is regarding Code

- [x] I am following clean code and Documentation and my code is well linted with flake8.

 - [ ] I am using external libraries and I have created requirements.txt in my project folder

- [x] Script is tested and running perfectly fine on my system

 - [ ] PR is regarding the documentation

acknowledgment
- [x]  I have tested my code and distributing it under GPL-3.0 License

### CODE REVIEW

**Comment by Punit-Choudhary** [comment]
Hey @helloshiv01 
This issue is not assigned to you yet!
Just drop a comment here: https://github.com/Punit-Choudhary/Python-beginner-scripts/issues/201
And I will assign it to you.

**Comment by helloshiv01** [comment]
#201

**Comment by Punit-Choudhary** [comment]
SPAM ⚠️
Deleted Header and not following CONTRIBUTING guidelines

**Comment by helloshiv01** [comment]
bro why you have marked my pr as a spam.

**Comment by helloshiv01** [comment]
Bro Please dont mark my pr as a spam.i have made sure to follow all the
guidelines mentioned by you.if i had made any mistake i will rectify
it.Thank you

**Pull request closed without merging**
