### PR TITLE
Adding chatbot

### PR DESCRIPTION
**Pull request by kodepirate**
# Pull Request Template

*CHAT-BOT*

### CODE REVIEW

**Comment by kodepirate** [comment]
Creaated the chatbot
Request you to merge it @Punit-Choudhary 
And add the hacktoberfest tag

**Comment by Punit-Choudhary** [comment]
Invalid ⚠️
- Please go through [CONTRIBUTING](https://github.com/Punit-Choudhary/Python-beginner-scripts/blob/main/CONTRIBUTING.md) and [CONTRIBUTE](https://github.com/Punit-Choudhary/Python-beginner-scripts/tree/main/CONTRIBUTE) before making Issue/PR
- Missing PR template
- Missing Issue number (must)
   - Mention the Assigned Issue regarding this PR

**Comment by kodepirate** [comment]
Don't add any spam or invalid tag
Ok Let me add @Punit-Choudhary

**Comment by Punit-Choudhary** [comment]
@kodepirate any updates?

**Pull request closed without merging**
